// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdyfousmzyhqswfdcrpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkeWZvdXNtenlocXN3ZmRjcnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MzIxMjEsImV4cCI6MjA1NDUwODEyMX0.oS3DT0z94g9HmAsiALbNziQ1Yh9a4Ch0IchQCOtoLcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);